export const types = {
    // Sync
    TASK_MANAGER_FILL_TASKS: 'TASK_MANAGER_FILL_TASKS',
    TASK_MANAGER_START_FETCHING_TASKS: 'TASK_MANAGER_START_FETCHING_TASKS',
    TASK_MANAGER_END_FETCHING_TASKS: 'TASK_MANAGER_END_FETCHING_TASKS',

    // Async
    TASK_MANAGER_FETCH_TASKS_ASYNC: 'TASK_MANAGER_FETCH_TASKS_ASYNC',
}
